baseURL = "https://dream-plus-posts.netlify.com/"
languageCode = "ja-jp"
defaultContentLanguage = "jp"
title = "備忘log"
theme = "dream-plus"

googleAnalytics = "UA-112332904-3"

enableRobotsTXT = true

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
  author = "YukiYamada"
  description = "Just a random blog for random stuff, mostly tech-related."
  avatar = "https://raw.githubusercontent.com/SasakiYuki/bibo-log/master/_bibo-log/static/snowman_white.png"
  motto = "Android Developer.Learning Android Kotlin-Spring Python-Django."

  favicon = "/img/defaultFav.ico"

  #Background Settings
  enableColorBG = true

  #Cards shown per page
  itemsPerPage = 4

  #Enable card view
  contentType = "cards"

  #Enable Twitter Emoji
  twitterEmoji=true

[social]
  email = "wacorggen@gmail.com"
  github = "SasakiYuki"
  medium = "wacorggen"
  twitter = "YukiYamadaJP"
  siteStartYear = 2018