baseURL = "https://sasakiyuki.github.io/"
title = "UtkarshVerma's Blog"
theme = "dream-plus"
themesDir = "../.."		#Don't use this, only for exampleSite
paginate = 4
enableRobotsTXT = true
disqusShortname = "dream-plus"

#Skip building these files
ignoreFiles = ["content/404.md", "content/about.md", "content/cards/\\.*"]

#Syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

#Enable Hugo Emoji Conversion
enableEmoji=true

[params]
	#Favicon for site
	favicon = "/img/defaultFav.ico"

	#Set whether you're hosting "cards" or "post"
	contentType = "posts"
	
	siteStartYear = 2018

	[params.author]
		name = "Utkarsh Verma"
		description = "Just a random blog for random stuff, mostly tech-related."
		avatar = "https://raw.githubusercontent.com/UtkarshVerma/blog/source/static/images/myavatar.jpg"
		motto = "A keen maker, programmer and an Instructables author."

	[params.features]
		#Enable Twitter Emoji
		twitterEmoji = true
		#Enable Table of Contents
		toc = true
		#Enable share card
		shareCard = true
		#Use custom CSS
		customCSS = ["https://cdn.rawgit.com/UtkarshVerma/hugo-dream-plus/ae11561d/exampleSite/static/css/highlight.css"]

	[params.background]
		colorBG = true

	#Tags settings
	[params.tags]
		enabled = true

	#Categories settings
	[params.categories]
		enabled = true

[social]
	email = "wacorggen@gmail.com"
	github = "SasakiYuki"
	medium = "wacorggen"
	twitter = "YukiYamadaJP"
	siteStartYear = 2018